


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."delete_pii_on_completion"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
begin
  if new."kda_status" = 1000 and old."kda_status" is distinct from new."kda_status" and new."customer_pii_id" is not null then
    update "public"."Process_Database"
    set "customer_pii_id" = null
    where "id" = new."id";

    delete from "public"."Customer_PII"
    where "id" = new."customer_pii_id";
  end if;

  return new;
end;
$$;


ALTER FUNCTION "public"."delete_pii_on_completion"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Customer_PII" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "customer_mail" "text" NOT NULL,
    "customer_f_name" "text",
    "customer_l_name" "text",
    "customer_salutation" "text",
    "melo" "text",
    "meter_number" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."Customer_PII" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Process_Database" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "execution_date" "date" NOT NULL,
    "submitted_at" "date",
    "cons_val" double precision,
    "prod_val" double precision,
    "kda_status" smallint DEFAULT '0'::smallint NOT NULL,
    "customer_label" "text",
    "reading_date" timestamp with time zone,
    "customer_pii_id" "uuid"
);


ALTER TABLE "public"."Process_Database" OWNER TO "postgres";


COMMENT ON TABLE "public"."Process_Database" IS 'This is a central Database for the Process';



ALTER TABLE "public"."Process_Database" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Process Database_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."access_tokens" (
    "process_id" bigint NOT NULL,
    "token_hash" "text" NOT NULL,
    "expires_at" timestamp with time zone DEFAULT ("now"() + '30 days'::interval) NOT NULL,
    "used_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."access_tokens" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."kda_status" (
    "status_id" bigint NOT NULL,
    "status" "text"
);


ALTER TABLE "public"."kda_status" OWNER TO "postgres";


COMMENT ON TABLE "public"."kda_status" IS 'This Table connects the status key to a status description';



ALTER TABLE "public"."kda_status" ALTER COLUMN "status_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."kda_status_status_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."submission_files" (
    "id" bigint NOT NULL,
    "process_id" bigint NOT NULL,
    "storage_path" "text",
    "file_type" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "obis_code" "text" NOT NULL,
    "file_name" "text",
    CONSTRAINT "submission_files_obis_code_check" CHECK (("obis_code" = ANY (ARRAY['1.8.0'::"text", '2.8.0'::"text"])))
);


ALTER TABLE "public"."submission_files" OWNER TO "postgres";


ALTER TABLE "public"."submission_files" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."submission_files_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Customer_PII"
    ADD CONSTRAINT "Customer_PII_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Process_Database"
    ADD CONSTRAINT "Process Database_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."access_tokens"
    ADD CONSTRAINT "access_tokens_pkey" PRIMARY KEY ("token_hash");



ALTER TABLE ONLY "public"."access_tokens"
    ADD CONSTRAINT "access_tokens_token_hash_key" UNIQUE ("token_hash");



ALTER TABLE ONLY "public"."kda_status"
    ADD CONSTRAINT "kda_status_pkey" PRIMARY KEY ("status_id");



ALTER TABLE ONLY "public"."submission_files"
    ADD CONSTRAINT "submission_files_one_per_obis_per_process" UNIQUE ("process_id", "obis_code");



ALTER TABLE ONLY "public"."submission_files"
    ADD CONSTRAINT "submission_files_pkey" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "send_portal_link_webhook" AFTER INSERT ON "public"."Process_Database" FOR EACH ROW EXECUTE FUNCTION "supabase_functions"."http_request"('https://addegojftivjzzqlsbmq.supabase.co/functions/v1/send-portal-link', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZGVnb2pmdGl2anp6cWxzYm1xIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTg2ODc3NCwiZXhwIjoyMDk1NDQ0Nzc0fQ.Ir9XfFl_LeG7ExFjLVP2EFiyouQ5xva0RX7SYLI4C8c"}', '{}', '5000');



CREATE OR REPLACE TRIGGER "trigger_cleanup_pii" AFTER UPDATE OF "kda_status" ON "public"."Process_Database" FOR EACH ROW WHEN ((("new"."kda_status" = 1000) AND ("old"."kda_status" IS DISTINCT FROM "new"."kda_status"))) EXECUTE FUNCTION "public"."delete_pii_on_completion"();



ALTER TABLE ONLY "public"."Process_Database"
    ADD CONSTRAINT "Process_Database_customer_pii_id_fkey" FOREIGN KEY ("customer_pii_id") REFERENCES "public"."Customer_PII"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Process_Database"
    ADD CONSTRAINT "Process_Database_kda_status_fkey" FOREIGN KEY ("kda_status") REFERENCES "public"."kda_status"("status_id");



ALTER TABLE ONLY "public"."access_tokens"
    ADD CONSTRAINT "access_tokens_process_id_fkey" FOREIGN KEY ("process_id") REFERENCES "public"."Process_Database"("id");



ALTER TABLE ONLY "public"."submission_files"
    ADD CONSTRAINT "submission_files_process_id_fkey" FOREIGN KEY ("process_id") REFERENCES "public"."Process_Database"("id");



ALTER TABLE "public"."Customer_PII" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Process_Database" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."access_tokens" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "authenticated_all_access_tokens" ON "public"."access_tokens" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "authenticated_all_process_database" ON "public"."Process_Database" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "authenticated_all_submission_files" ON "public"."submission_files" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "authenticated_select_kda_status" ON "public"."kda_status" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."kda_status" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."submission_files" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."delete_pii_on_completion"() TO "anon";
GRANT ALL ON FUNCTION "public"."delete_pii_on_completion"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."delete_pii_on_completion"() TO "service_role";


















GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."Customer_PII" TO "anon";
GRANT ALL ON TABLE "public"."Customer_PII" TO "authenticated";
GRANT ALL ON TABLE "public"."Customer_PII" TO "service_role";



GRANT ALL ON TABLE "public"."Process_Database" TO "authenticated";
GRANT ALL ON TABLE "public"."Process_Database" TO "service_role";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "public"."Process_Database" TO "anon";



GRANT ALL ON SEQUENCE "public"."Process Database_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Process Database_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Process Database_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."access_tokens" TO "authenticated";
GRANT ALL ON TABLE "public"."access_tokens" TO "service_role";



GRANT ALL ON TABLE "public"."kda_status" TO "authenticated";
GRANT ALL ON TABLE "public"."kda_status" TO "service_role";



GRANT ALL ON SEQUENCE "public"."kda_status_status_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."kda_status_status_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."kda_status_status_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."submission_files" TO "authenticated";
GRANT ALL ON TABLE "public"."submission_files" TO "service_role";



GRANT ALL ON SEQUENCE "public"."submission_files_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."submission_files_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."submission_files_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































revoke select on table "public"."Customer_PII" from "anon";

revoke references on table "public"."Process_Database" from "anon";

revoke trigger on table "public"."Process_Database" from "anon";

revoke truncate on table "public"."Process_Database" from "anon";

revoke delete on table "public"."access_tokens" from "anon";

revoke insert on table "public"."access_tokens" from "anon";

revoke references on table "public"."access_tokens" from "anon";

revoke select on table "public"."access_tokens" from "anon";

revoke trigger on table "public"."access_tokens" from "anon";

revoke truncate on table "public"."access_tokens" from "anon";

revoke update on table "public"."access_tokens" from "anon";

revoke delete on table "public"."kda_status" from "anon";

revoke insert on table "public"."kda_status" from "anon";

revoke references on table "public"."kda_status" from "anon";

revoke select on table "public"."kda_status" from "anon";

revoke trigger on table "public"."kda_status" from "anon";

revoke truncate on table "public"."kda_status" from "anon";

revoke update on table "public"."kda_status" from "anon";

revoke delete on table "public"."submission_files" from "anon";

revoke insert on table "public"."submission_files" from "anon";

revoke references on table "public"."submission_files" from "anon";

revoke select on table "public"."submission_files" from "anon";

revoke trigger on table "public"."submission_files" from "anon";

revoke truncate on table "public"."submission_files" from "anon";

revoke update on table "public"."submission_files" from "anon";


